apiVersion: v1
kind: Service
metadata:
  name: {{ include "diplom-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "diplom-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "diplom-app.selectorLabels" . | nindent 4 }}
